MAIL_USERNAME: 3349585586@qq.com
MAIL_PASSWORD: devdev
MAIL_ADDRESS: smtp.qq.com
MAIL_PORT: 25
DOMAIN_NAME: qq.com
MAIL_AUTH: login

ADMIN_NAME: admin
ADMIN_EMAIL: admin@tool-providers.com
ADMIN_PASSWORD: admin
ROLES: [admin, investor, leader]

# GOOGLE ANYLITCS
GA_ID: ''
GA_URL: ''

# set system locale en or zh-CN, default is zh-CN
LOCALE: zh-CN

# SECRET_KEY_BASE
SECRET_KEY_BASE: ''
# sidekiq namespace
SIDEKIQ_NAMESPACE: tool-providers
# built-in test enable 1 / disable 0
BIT: 0
