# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f30a0bfaa10404b39a6790c9c1dafdc40ca1bd2ad1aecb65e3643bd801676c4dddeca99ade9166248deb9c683f1f0712f5852d25050ec53cee7968f70737e51e

test:
  secret_key_base: 26137d0ed8109adeaa656047d61a8e95c72fdcbc87b75cf15698cb0edde8056a2469260133823092c7c8621d8b0675487fe8881b4681704a84b97131f7eb09d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
